---
title: "HW class 6"
author: "McKenzie Mai (A16646664)"
date: "2024-04-27"
output:
  pdf_document: default
  html_document: default
---

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```


> Q6. How would you generalize the original code above to work with any set of input protein structures?

Function that helps analyze protein drug interactions by reading in any protein PDB data and outputs a plot for the specified protein:
```{r}
analyze <- function(file) {
  # Function to read, trim, and extract B-factor values
  read_trim_extract <- function(file) {
    # Reads pdb file
    pdb <- read.pdb(file)
    # Trims pdb file to chain A and selects type of atom (alpha carbon) for trimming
    chain <- trim.pdb(pdb, chain="A", elety="CA")
    # Extracts  B-factor values
    chain$atom$b
  }
  
  # Plots B-factor trends
  plotb3(read_trim_extract(file), sse=trim.pdb(read.pdb(file), chain="A", elety="CA"), 
         typ="l", ylab="Bfactor")
}

# Example output using pdb file identifiers 
analyze("4AKE")
```
